theme = "catppuccin_frappe"

[editor]
bufferline = "multiple"
line-number = "relative"
color-modes = true
cursorline = true

[editor.statusline]
left = [
  "mode",
  # "separator",
  "spacer",
  "version-control",
  "spinner",
  "read-only-indicator",
  "file-modification-indicator",
  "register",
]
right = [
  "diagnostics",
  "selections",
  "position",
  "total-line-numbers",
  # position-percentage,
]
# separator = "|"

[editor.cursor-shape]
insert = "bar"
# normal = "block"
# select = "underline"

# [editor.whitespace.render]
# space = "all"
[editor.whitespace.characters]
space = "·"

[editor.indent-guides]
render = true
character = "╎"

[keys.normal]
C-P = "command_palette"
C-p = "file_picker"
C-v = "paste_clipboard_after"
C-c = "yank_to_clipboard"
# "C-tab" = ":buffer-next"
# "C-/" = ["toggle_comments"]
A-s = ":w"
A-w = ":buffer-close"
A-q = ":quit"
"A-/" = "toggle_comments"
"A-right" = ":buffer-next"
"A-left" = ":buffer-previous"

[keys.insert]
A-s = ["normal_mode", ":w"]
C-p = "file_picker"

