# If this doesn't work, you might be on a older release version which handles this differently.
# Try using [language.config.check] instead of [language-server.rust-analyzer.config.check]
[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]
indent = { tab-width = 4, unit = "    " }

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/usr/local/lib/node_modules/@vue/language-server"
languages = ["vue"]
